# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5af5d5d44713f74d8b4cf89038b401574de981dafc1350772fede8691208b1b09c7f36aae3b40c8ee2c9f2e311c58a5d22d13e4ecfb8288e1469b182d236b2c2

test:
  secret_key_base: d2c559e4de7a3eec8384d218b6e9c6c6659b5084d970a21ad5cf4d019f5cef1b5e8311fce7f333ccf1538595aa78ed88ba1bafbf74180e53ee54a0655cbaf59e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
